<a href="https://colab.research.google.com/github/chaitu713/data-analysis-with-python-numpy-pandas/blob/master/1%20numpy-assignment-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Package Imports

In [1]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [2]:
my_list = [x * 10 for x in range(1, 11)]

In [3]:
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [4]:
my_list_arr = np.array(my_list)

In [5]:
my_list_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [6]:
my_list_arr.ndim

1

In [8]:
my_list_arr.shape

(10,)

In [9]:
my_list_arr.size

10

In [10]:
my_list_arr.dtype

dtype('int64')

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [11]:
np_arr = np.arange(10, 110, 10)

In [12]:
np_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [13]:
np_arr_2d = np_arr.reshape(5, 2)

In [14]:
np_arr_2d

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [15]:
from numpy.random import default_rng

In [16]:
rng = default_rng(2022)

In [20]:
random_array = rng.random(9).reshape(3, 3)

In [24]:
random_array

array([[0.98862926, 0.96919869, 0.25697153],
       [0.55876211, 0.24234798, 0.32202029],
       [0.89135975, 0.94611366, 0.72253931]])

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second element of the third row.

Thanks!


In [32]:
random_array

array([[0.98862926, 0.96919869, 0.25697153],
       [0.55876211, 0.24234798, 0.32202029],
       [0.89135975, 0.94611366, 0.72253931]])

In [37]:
random_array[0:2]

array([[0.98862926, 0.96919869, 0.25697153],
       [0.55876211, 0.24234798, 0.32202029]])

In [43]:
random_array[:,0]

array([0.98862926, 0.55876211, 0.89135975])

# **OR**

In [44]:
random_array.T[0]

array([0.98862926, 0.55876211, 0.89135975])

In [45]:
random_array[2, 1]

0.9461136638059269

# **OR**

In [46]:
random_array[2][1]

0.9461136638059269

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [58]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

In [59]:
total = prices + 5

total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [60]:
discount_pct = random_array[0:2, :].reshape(1, 6)

discount_pct

array([[0.98862926, 0.96919869, 0.25697153, 0.55876211, 0.24234798,
        0.32202029]])

In [61]:
pct_owned = 1 - discount_pct

pct_owned

array([[0.01137074, 0.03080131, 0.74302847, 0.44123789, 0.75765202,
        0.67797971]])

In [63]:
final_amnt = pct_owned * total

final_amnt.round(2)

array([[ 0.12,  0.37, 20.43, 46.33,  7.57, 37.28]])

# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [65]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

print(f"products : {products}")
print(f"prices : {prices}")

products : ['salad' 'bread' 'mustard' 'rare tomato' 'cola' 'gourmet ice cream']
prices : [ 5.99  6.99 22.49 99.99  4.99 49.99]


In [67]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [72]:
mask = (prices > 25) | (products == 'cola')

fancy_feast_special = products[mask]

fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [73]:
shipping_cost = np.where(prices > 20, 0, 5)

shipping_cost

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [74]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [78]:
prices.sort()

max_three = prices[3:]

max_three

array([22.49, 49.99, 99.99])

In [82]:
print(f"mean of top three prices is : {max_three.mean()}")
print(f"min of top three prices is : {max_three.min()}")
print(f"max of top three prices is : {max_three.max()}")
print(f"median of top three prices is : {np.median(max_three)}")

mean of top three prices is : 57.49
min of top three prices is : 22.49
max of top three prices is : 99.99
median of top three prices is : 49.99


In [83]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [86]:
unique_price_tiers = np.unique(price_tiers)

print(unique_price_tiers)

print(f"No. of unique price tiers : {unique_price_tiers.size}")

['budget' 'luxury' 'mid-tier']
No. of unique price tiers : 3


# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [88]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "/content/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [90]:
print(f"family array : {family_array}")

print(f"sales array : {sales_array}")

family array : ['EGGS' 'FROZEN FOODS' 'GROCERY I' 'GROCERY II' 'HARDWARE'
 'HOME AND KITCHEN I' 'HOME AND KITCHEN II' 'HOME APPLIANCES' 'HOME CARE'
 'LADIESWEAR' 'LAWN AND GARDEN' 'LINGERIE' 'LIQUOR,WINE,BEER' 'MAGAZINES'
 'MEATS' 'PERSONAL CARE' 'PET SUPPLIES' 'PLAYERS AND ELECTRONICS'
 'POULTRY' 'PREPARED FOODS' 'PRODUCE' 'SCHOOL AND OFFICE SUPPLIES'
 'SEAFOOD' 'AUTOMOTIVE' 'BABY CARE' 'BEAUTY' 'BEVERAGES' 'BOOKS'
 'BREAD/BAKERY' 'CELEBRATION' 'CLEANING' 'DAIRY' 'DELI' 'EGGS'
 'FROZEN FOODS' 'GROCERY I' 'GROCERY II' 'HARDWARE' 'HOME AND KITCHEN I'
 'HOME AND KITCHEN II' 'HOME APPLIANCES' 'HOME CARE' 'LADIESWEAR'
 'LAWN AND GARDEN' 'LINGERIE' 'LIQUOR,WINE,BEER' 'MAGAZINES' 'MEATS'
 'PERSONAL CARE' 'PET SUPPLIES' 'PLAYERS AND ELECTRONICS' 'POULTRY'
 'PREPARED FOODS' 'PRODUCE' 'SCHOOL AND OFFICE SUPPLIES' 'SEAFOOD'
 'AUTOMOTIVE' 'BABY CARE' 'BEAUTY' 'BEVERAGES' 'BOOKS' 'BREAD/BAKERY'
 'CELEBRATION' 'CLEANING' 'DAIRY' 'DELI' 'EGGS' 'FROZEN FOODS' 'GROCERY I'
 'GROCERY II' 'HARDWARE' 'HOM

In [97]:
produce_array = sales_array[family_array == 'PRODUCE']

print(produce_array)
print('\n')
print(f"The size of array is : {produce_array.size}")

[1662.394  447.064 2423.944  962.866 1236.404  298.441 1077.44  3404.531
  962.96   279.505 1852.786 1089.319  726.516 7860.031  446.038 1155.385
  120.202  862.092  473.952  254.263 1272.755 2775.771 2030.762 1657.432
 2339.906  722.333 1567.843 2458.456  673.885 8834.15 ]


The size of array is : 30


In [98]:
rng = np.random.default_rng(2022)

random_array = rng.random(30)

produce_sample = produce_array[random_array < 0.5]

print(produce_sample)
print('\n')
print(f"The size of produce sample array is : {produce_sample.size}")

[1662.394  447.064  962.866 1077.44  3404.531  962.96  1089.319 7860.031
  446.038 1272.755 2775.771 2339.906  722.333 1567.843 2458.456  673.885
 8834.15 ]


The size of produce sample array is : 17


In [99]:
mean = produce_sample.mean()

print(f"Mean of the sample array is : {mean}")

Mean of the sample array is : 2268.102470588235


In [100]:
median = np.median(produce_sample)

print(f"The median of sample array is : {median}")

The median of sample array is : 1272.755


In [111]:
new_produce = np.where(produce_sample > median, np.where(produce_sample > mean, 'above-both', 'above-median below-mean'), np.where(produce_sample > mean, 'below-median above-mean', 'below-both'))

print(f"produce_sample array is : {produce_sample}")
print('\n')
print(f"The median is : {median}")
print('\n')
print(f"The mean is : {mean}")
print('\n')
print(f"new_produce array is : {new_produce}")

produce_sample array is : [1662.394  447.064  962.866 1077.44  3404.531  962.96  1089.319 7860.031
  446.038 1272.755 2775.771 2339.906  722.333 1567.843 2458.456  673.885
 8834.15 ]


The median is : 1272.755


The mean is : 2268.102470588235


new_produce array is : ['above-median below-mean' 'below-both' 'below-both' 'below-both'
 'above-both' 'below-both' 'below-both' 'above-both' 'below-both'
 'below-both' 'above-both' 'above-both' 'below-both'
 'above-median below-mean' 'above-both' 'below-both' 'above-both']
